services:
  - type: web
    name: dimash-qurt-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /ping
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MODEL_PATH
        value: models/dimash_qurt_classifier2.pkl
      - key: CORS_ORIGINS
        value: http://localhost:3000,http://127.0.0.1:3000
      - key: CONFIDENCE_THRESHOLD
        value: "0"
